### ISSUE TITLE
softImpute in rsparse

### ISSUE THREAD

**Issue by dselivanov** [RoheLab/fastadi#11]
Thanks for citing rsparse in readme!
Just FYI, softimpute for sparse matrices is implemented in rsparse pkg as well (somewhat more efficient compared to original softimpute as implemented more carefully).

**Comment by alexpghayes** [comment]
Good to know, will update the README! `AdaptiveImpute` is very similar algorithmically to `softImpute` and we'd low to improve the efficiency of our implementation. Can I ping you in a couple weeks once I've done some more work on the package for implementation advice?

I'm also curious if you know of any goodR  implementations of SVD++ or other implicit feedback that I could take a look at!

**Comment by dselivanov** [comment]
> Good to know, will update the README! AdaptiveImpute is very similar algorithmically to softImpute and we'd low to improve the efficiency of our implementation. Can I ping you in a couple weeks once I've done some more work on the package for implementation advice?

sure

> I'm also curious if you know of any goodR implementations of SVD++ or other implicit feedback that I could take a look at!

I'm not sure about SVD++ and not sure if it is widely used nowadays. 

There is implementation of "Bayesian Personalized Ranking from Implicit Feedback" and "Weighted Approximately Ranked Pairwise" (WARP) loss for matrix factorization and matrix factorization with side information [LightFM](https://github.com/lyst/lightfm) in rsparse - https://github.com/rexyai/rsparse/blob/595eace8f0fef413b2f296a88435db72b0bdca7b/R/model_RankMF.R#L7
But no documentation so far.

**Comment by alexpghayes** [comment]
Hey @dselivanov, I've managed to clean things up and hopefully now have a readable single-threaded implementation. The tl;dr is the computations for `AdaptiveImpute` are almost identical to those for `softImpute` -- what was the key to speeding up `softImpute`? It seems like `rsparse` uses multi-threaded matrix operations -- can you point me to some resources on how I can start using those myself?

**Comment by dselivanov** [comment]
You can just load rsparse with `library(rsparse)` and see if things will get faster. It overloads S4 methods sparse-dense matrix multiplication.

**Comment by alexpghayes** [comment]
Thanks!

**Comment by dselivanov** [comment]
Now I suggest using [MatrixExtra](https://github.com/david-cortes/MatrixExtra). It provides a lot of high-performance functions for sparse matrices operations (both CSC and CSR). Also works with single precision floats from [float](https://cran.r-project.org/web/packages/float/) package. Give it a try!
